---
- name: System update and user setup
  hosts: prox-vm-test-ansible
  become: yes

  tasks:
    - block:
        # Обновление кэша пакетов
        - name: Update apt package cache
          apt:
            update_cache: yes
            cache_valid_time: 3600
          tags: update
      tags: update-cache
