---
- name: Install packages and start services
  hosts: prox-vm-test-ansible
  become: yes

  tasks:
    - block:
        # Обновляем индекс локального репозитория
        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600
      tags: update-cache

    - block:
        # Устанавливаем необходимыне пакеты
        - name: Install required packages
          apt:
            name:
              - nginx
              - apache2-utils
              - certbot
              - python3-certbot-nginx
            state: latest # Если нужно установить или обновить установленный пакет до последней версии
            # state: present                                  # Если нужно проверить наличие пакета без обновления до последней версии
            # force: yes                                      # Только если нужно принудительно установить или обновить пакет

        # Запускаем и ставим в автозагрузку сервис nginx
        - name: Start Nginx and Enable on every boot
          service:
            name: nginx
            state: started
            enabled: yes
      tags: install-nginx
# Если команда смены пароля не сработает нужно запустить команду - ansible-playbook 09.1_apt_install_nginx.yml --ask-become-pass
