---
- name: System update and upgrade before ferst settings.
  hosts: #all
  become: yes

  vars_prompt:
    # Интерактивно запрашиваем у пользователя пароль для переменной root_password
    - name: root_password
      prompt: "Enter new root password"
      private: yes

    # Интерактивно запрашиваем у пользователя пароль для переменной ar5_password
    - name: ar5_password
      prompt: "Enter password for user ar5"
      private: yes


  tasks:
    - block:
        # Обновляем индекс локального репозитория и обновляем пакеты
        - name: Update apt package cache and upgrade packages
          apt:
            update_cache: yes
            cache_valid_time: 3600
            upgrade: yes
            autoremove: yes
            autoclean: yes

    - block:
        # Меняем пароль пользователя root
        - name: Changing password user root
          ansible.builtin.user:
            name: root
            password: "{{ root_password | password_hash('sha512') }}"

    - block:
        # Создаем пользователя ar5 с домашней директорией
        - name: Create user ar5 with home and bash shell
          user:
            name: ar5
            state: present
            groups: sudo
            append: yes
            shell: /bin/bash
            create_home: yes

        # Меняем пароль пользователя ar5
        - name: Changing password user ar5
          user:
            name: ar5
            password: "{{ ar5_password | password_hash('sha512') }}"

        # Проверяем пользователя ar5 в /etc/passwd
        - name: Show ar5 user entry from /etc/passwd
          command: grep '^ar5:' /etc/passwd
          register: ar5_passwd
          changed_when: false

        - name: Display passwd entry for ar5
          debug:
            var: ar5_passwd.stdout

        # Проверяем группы в которые входит пользователь ar5
        - name: Get groups of user ar5
          command: groups ar5
          register: ar5_groups
          changed_when: false

        - name: Display groups of ar5
          debug:
            var: ar5_groups.stdout














    - block:
        # Установка настройка и запуск Docker и Docker Compose - официальный рекомендованный способ
        - name: Install prerequisite packages
          apt:
            name:
              - ca-certificates
              - curl
            state: present

        - name: Create directory for Docker keyrings
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download Docker GPG key
          get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'

        - name: Add Docker repository to apt sources
          apt_repository:
            repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
            filename: docker
            state: present
            update_cache: yes

        - name: Install Docker packages
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: Ensure Docker service is started and enabled
          systemd:
            name: docker
            state: started
            enabled: yes

      

