---
- name: Install packages
  hosts: prox-vm-test-ansible
  become: yes

  tasks:
    - block:
        # Добавляем настройки в конфиг фаил nano /etc/nanorc
        - name: Add customized Nano editor settings to /etc/nanorc
          lineinfile:
            path: /etc/nanorc
            insertafter: EOF # Указывает что нужно внести изменения в конец фаила
            line: "{{ item }}"
          loop:
            - "set titlecolor bold,white,blue"
            - "set promptcolor lightwhite,grey"
            - "set statuscolor bold,white,green"
            - "set errorcolor bold,white,red"
            - "set spotlightcolor black,lightyellow"
            - "set selectedcolor lightwhite,magenta"
            - "set stripecolor ,yellow"
            - "set scrollercolor cyan"
            - "set numbercolor cyan"
            - "set keycolor cyan"
            - "set functioncolor green"
            - "set mouse"
            - 'include "/usr/share/nano/*.nanorc"'
          notify: Reload nano config if needed
      tags: configure-nano

  handlers:
    - name: Reload nano config if needed
      debug:
        msg: "Настройки nano обновлены. Перезапуск nano не требуется."
# Если команда смены пароля не сработает нужно запустить команду - ansible-playbook 15_setting_nano.yml --ask-become-pass
